name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests and coverage
        run: npm test

      - name: Upload coverage to Coveralls
        run: npm run coverage && npx coveralls
        env:
          COVERALLS_REPO_TOKEN: ZVksBYGMLKfi7AyjqNEj2tdVyx9t3IAie
